learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
"""Defines URL patterns for learning_logs"""
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Homepage
    # 'name' specifies this url pattern incase for future use
    path('', views.index, name='index'),
    path('topics/', views.topics, name='topics'),
    # Detail page for a single topic page""
    # Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    path('new_topic/', views.new_topic, name='new_topic'),
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
"""Defines url patterns for users"""
from django.urls import path, include
import django.contrib.auth.urls
from . import views

app_name = 'users'

urlpatterns = [
	#include default auth urls
	path('', include('django.contrib.auth.urls')),
	path('register/', views.register, name='register'),
	path('about_me', views.about_me, name='about_me'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
   """A topic the user is learning about"""
   text = models.CharField(max_length=200)
   date_added = models.DateTimeField(auto_now_add=True)
   owner = models.ForeignKey(User, on_delete=models.CASCADE)

   def __str__(self):
      """Return a string representation of the model"""
      return self.text


class Entry(models.Model):
   """Something specific learned about a topic"""
   topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
   text = models.TextField()
   date_added = models.DateTimeField(auto_now_add=True)

   class Meta:
      verbose_name = 'entries'

   def __str__(self):
      """Return a string representation of the Entry model"""
      if len(self.text) > 50:
         return f'{self.text[:50]}...'.capitalize()
      else:
         return f'{self.text[:50]}'.capitalize()

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from . models import Topic, Entry


class TopicForm(forms.ModelForm):
   class Meta:
      model = Topic
      fields = ['text']
      labels = {'text': ''}


class EntryForm(forms.ModelForm):
   class Meta:
      model = Entry  # specify the model of the form structure
      fields = ['text']
      labels = {'text': 'Entry:'}
      widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from . models import Topic, Entry
from . forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
   """The home page for Learning Log"""
   return render(request, 'index.html')

@login_required
def topics(request):
   """the page to display all topics"""
   topics = Topic.objects.filter(owner=request.user).order_by('date_added')
   # A context is a dict that is used to hold the data we wil use (topics) and 'topics' as key to represent our data in the our templates dynamically.
   context = {'topics': topics}
   return render(request, 'topics.html', context)

@login_required
def topic(request, topic_id):
   """Show a single topic and all its entries"""
   topic = Topic.objects.get(id=topic_id)
   #make sure the topic belongs to the current user
   if topic.owner != request.user:
      raise Http404
   entries = topic.entry_set.order_by('-date_added')
   context = {'topic': topic, 'entries': entries}
   return render(request, 'topic.html', context)



@login_required
def new_topic(request):
   """Add a new topic"""
   if request.method != 'POST':
      # No data submitted; create a blank form
      form = TopicForm()
   else:
      # POST data submitted; process data
      form = TopicForm(data=request.POST)
      # check submitted data validity
      if form.is_valid():
         # write data to our database
         new_topic = form.save(commit=False)
         new_topic.owner = request.user
         new_topic.save()
         form.save()
         # redirect back to topics page after saving the new topic added
         return redirect('learning_logs:topics')

   # Display a blank or invalid form
   context = {'form': form}
   return render(request, 'new_topic.html', context)

@login_required
def new_entry(request, topic_id):
   """Add a new entry for a particular topic"""
   topic = Topic.objects.get(id=topic_id)
   if request.method != 'POST':
      # No data submitted; create a blank form
      form = EntryForm()
   else:
      # POST data submitted; process data
      form = EntryForm(data=request.POST)
      # check submitted data validity
      if form.is_valid():
         # write data to our database
         new_entry = form.save(commit=False)
         new_entry.topic = topic
         new_entry.save()
         # redirect back to topics page after saving the new topic added
         return redirect('learning_logs:topic', topic_id=topic_id)
   # Display a blank or invalid form
   context = {'topic': topic, 'form': form}
   return render(request, 'new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
      """Edit an existing entry"""
      entry = Entry.objects.get(id=entry_id)
      topic = entry.topic
      if topic.owner != request.user:
         raise Http404
      if request.method != 'POST':
         # initial request; pre-fill form with the current entry.
         form = EntryForm(instance=entry)
      else:
         # POST data submitted; process data
         form = EntryForm(instance=entry, data=request.POST)
         if form.is_valid:
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

      context = {'entry': entry, 'topic': topic, 'form': form}
      return render(request, 'edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.contrib.auth.decorators import login_required


def register(request):
   """Register a new user."""
   if request.method != 'POST':
     # Display blank registration form.
      form = UserCreationForm()
   else:
     # Process completed form.
      form = UserCreationForm(data=request.POST)
      if form.is_valid():
         new_user = form.save()
         # Log the user in and then redirect to home page.
         login(request, new_user)
         return redirect('learning_logs:index')
   # Display a blank or invalid form.
   context = {'form': form}
   return render(request, 'registration/register.html', context)


def about_me(request):
   return render(request, 'about_me.html')

learning_logs/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>learning_log</title>
</head>

<body>
	<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
		<a class="navbar-brand" href="{% url 'learning_logs:index'%}">
			E-Logbook</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
			aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span></button>
		<div class="collapse navbar-collapse" id="navbarCollapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a class="nav-link" href="{% url 'learning_logs:topics'%}">
						Topics</a></li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:about_me'%}">
						About Developer</a></li>
			</ul>
			<ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
				<li class="nav-item">
					<span class="navbar-text">Hello, {{ user.username }}.</span>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
				</li>

				{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:register' %}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
				{% endif %}
			</ul>
		</div>
	</nav>
	<main role="main" class="container">
		<div class="pb-2 mb-2 border-bottom">
			{% block page_header %}{% endblock page_header %}
		</div>
		<div>
			{% block content %}{% endblock content %}
		</div>
	</main>
	<script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
	<script src="./static/js/jquery_umcompressed.js"></script>
	<script src="./static/js/jquery.js"></script>
	<script src="./static/js/popper.js"></script>
	<script src="./static/js/boostrap.min.js"></script>
</body>

</html>

learning_logs/templates/edit_entry.html
{% extends "base.html" %}
{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
	<p>Edit entry:</p>
	<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Save changes</button>
	</form>
{% endblock content %}

learning_logs/templates/index.html
{%extends "base.html"%}
{% block page_header %}
	<div class="jumbotron">
		<h1 class="display-3">Hi, Let us help you track your learning progress.</h1>
		<p class="lead">Make your own Learning Log, and keep a list of the
			topics you're learning about. Whenever you learn something new
		about a topic, make an entry summarizing what you've learned.</p>
		<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
		role="button">Get started &raquo;</a>
	</div>
{% endblock page_header %}

learning_logs/templates/new_entry.html
{% extends "base.html" %}
{% block content %}

	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

	<p>Add a new entry:</p>

	<form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" class="btn btn-primary">Add entry</button>
	</form>
{% endblock content %}

learning_logs/templates/new_topic.html
{% extends "base.html" %}
{% block content %}
	
	<div class="col">
		<p>Add a new topic</p>
		<form action="{% url 'learning_logs:new_topic' %}" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-primary">Add topic</button>
		</form>
	</div>
{% endblock content %}

learning_logs/templates/topic.html
{% extends "base.html" %}
	{% block page_header %}
		<h3>Topic: {{topic}}</h3>
	{% endblock page_header %}
	{% block content %}
	<p>Entries:</p>
	<ul>
		<p>
			<a href="{% url 'learning_logs:new_entry' topic.id %}">Add entry</a>
		</p>
		{% for entry in entries %}
			<div class="card mb-3">
				<h4 class="card-header">
				{{ entry.date_added|date:'M d, Y H:i' }}
				<small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
				edit entry</a></small>
				</h4>
				<div class="card-body">
					{{ entry.text|linebreaks }}
				</div>
			</div>
			{% empty %}
			<p>There are no entries for this topic yet.</p>
		{% endfor %}
	</ul>
{% endblock content %}

learning_logs/templates/topics.html
{% extends "base.html"%}
{% block page_header %}
<h1>Topics</h1>
{% endblock page_header %}

{% block content %}
	<ul>
		{% for topic in topics %}
			<li><h3>
				<a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>
				
			</h3></li>
		{% empty %}
			<li><h3>No topics have been added yet.</h3></li>
		{%endfor%}

		</ul>
		<h3><a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a></h3>
	{% endblock content%}

users/templates/about_me.html
{% extends "base.html"%}
{% load static %}
{% block page_header %}
	<h2>Hi, I am Abdurrahaman!</h2>
{% endblock page_header %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="rounded float-left mr-4">
	<img src="{% static 'assets/my_image.jpg' %}" class="img-fluid" alt="Responsive image" id="mypic" height="500px" width="500px">
</div>
<div class="container">
	<h4><p>I am glad that you're here!<br></br>
		I'm a junior upcoming web developer and I'm very passionate about web application software development using the powerful python 3 framework django.<br></br>
		All because I love the (dot) .com stuff coupled with pythonic way of life!<br></br>
		I created this web application in order to help students especially my colleagues track their learning!<br></br>
		In case of any feed back you can email me at
		<a href="mailto:Abdurrahamanabdullahi20@gmail.com">Abdurrahamanabdullahi20@gmail.com</a> or visit my website at
		<a href="https://cleverpythonista.com">clever pythonista</a>
		Happy learning!
	</p></h4>
	</div>
{% endblock content %}

users/templates/register.html
{% extends "base.html" %}
{% block content %}
	<form method="post" action="{% url 'users:register' %}">
		{% csrf_token %}
		{{ form.as_p }}
		<button name="submit">Register</button>
		<input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
	</form>
{% endblock content %}